name: Build CI

on: 
  push:
    branches: [test, main]
  pull_request: 
    branches: [test, main]

jobs: 
  style-check: 
    runs-on: macos-latest
    steps: 
    - name: Checkout code
      uses: actions/checkout@v2
    - name: MVN check 
      run: |
        cd IndividualProject
        mvn checkstyle:check

    - name: PMD check
      run: |
        cd IndividualProject
        mvn pmd:check

  run-unit-test: 
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run unit test
      run: |
        cd IndividualProject
        mvn test
    - name: Check test result
      if: failure()
      run: echo "Unit tests failed!" && exit 1
