name: Build CI

on: 
  push:
    branches: [main]
  pull_request: 
    branches: [main]

jobs: 
  style-check: 
    runs-on: macos-latest
    steps: 
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: mvn check 
      run: |
        cd IndividualProject
        mvn checkstyle:check

    - name: pmd check
      run: pmd check -f text -R rulesets/java/quickstart.xml -d .
