name: Build CI

on: 
  push:
    branches: [main]
  pull_request: 
    branches: [main]

jobs: 
  style-check: 
    runs-on: macos-latest
    steps: 
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: MVN check 
      run: |
        cd IndividualProject
        mvn checkstyle:check

    - name: PMD check
      run: |
        mvn pmd:check

