name: Build CI

on: 
  push:
    branches: [test, main]
  pull_request: 
    branches: [test, main]

jobs: 
  style-check: 
    runs-on: macos-latest
    steps: 
    - name: Checkout code
      uses: actions/checkout@v2
    - name: MVN check 
      run: |
        cd IndividualProject
        mvn checkstyle:check

    - name: PMD check
      run: |
        cd IndividualProject
        mvn pmd:check

  test-build: 
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run build
      run: |
        cd IndividualProject
        mvn clean install  # Ensure to install dependencies

        # Run Spring Boot in the background using 'setsid' to start in a new process group
        (setsid mvn spring-boot:run -Dspring-boot.run.arguments="setup" | tee output.log) &

        # Store the PID of the last background process
        CMD_PID=$!

        # Monitor the output for "System Setup"
        while true; do
          if grep -q "System Setup" output.log; then
            echo "Detected 'System Setup'. Sending Ctrl+C..."
            kill -2 $CMD_PID  # Send SIGINT to gracefully stop the process
            break
          fi
          sleep 1  # Wait for a second before checking again
        done

        # Wait for the command to finish
        wait $CMD_PID
