name: Build CI

on: 
  push:
    branches: [main]
  pull_request: 
    branches: [main]

jobs: 
  style-check: 
    runs-on: macos-latest
    steps: 
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: MVN check 
      run: |
        cd IndividualProject
        mvn checkstyle:check

    - name: Install PMD
      run: |
        curl -OL https://github.com/pmd/pmd/releases/download/pmd_releases%2F7.5.0/pmd-dist-7.5.0-bin.zip
        unzip pmd-dist-7.5.0-bin.zip
        alias pmd="$HOME/pmd-bin-7.5.0/bin/pmd"

    - name: pmd check
      run: pmd check -f text -R rulesets/java/quickstart.xml -d .
