name: Build CI

on: 
  push:
    branches: [test, main]
  pull_request: 
    branches: [test, main]

jobs: 
  style-check: 
    runs-on: macos-latest
    steps: 
    - name: Checkout code
      uses: actions/checkout@v2
    - name: MVN check 
      run: |
        cd IndividualProject
        mvn checkstyle:check

    - name: PMD check
      run: |
        cd IndividualProject
        mvn pmd:check

  test-build: 
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run build
      run: |
        cd IndividualProject
        mvn clean install  # Ensure to install dependencies

        # Start Spring Boot in the background
        nohup mvn spring-boot:run -Dspring-boot.run.arguments="setup" > output.log 2>&1 &

        # Wait for the process to start
        sleep 5

        # Find the Spring Boot process ID
        CMD_PID=$(ps aux | grep 'spring-boot:run' | grep -v grep | awk '{print $2}')

        # Monitor the output for "System Setup"
        while true; do
          if grep -q "System Setup" output.log; then
            echo "Detected 'System Setup'. Sending SIGINT..."
            kill -2 $CMD_PID  # Send SIGINT to the Spring Boot process
            break
          fi
          sleep 1  # Wait for a second before checking again
        done

        # Wait for the command to finish
        wait $CMD_PID
